Bug/dataframe datetimeindex not working with decimals
DHI/mikeio1d pull request #57
Opened 2023-09-13 13:59 UTC by ryan-kipawa

This PR is to address #56.

Previously milliseconds were not included from .NET, but now they're included. It seems .NET v5 doesn't support microseconds, whereas Python's datetime object supports microseconds but not milliseconds. So, we won't have a 1-1 conversion each way, but I think it's close enough for the use cases.

2023-09-14 12:22 UTC, ecomodeller requested changes
The current test involves reading an actual file, thus it is a kind of integration or end-to-end test.

Please add unit tests as well, that verifies the expected behavior of the datetime conversion from dotnet to Python and vice versa, e.g.:
```python
def test_datetime_conversion_preserves_millisecond_precision():

    dtstr = "2021-01-01 00:00:00.123"

    dotnet_dt = System.DateTime.Parse(dtstr)
    assert dotnet_dt.Millisecond == 123
    py_dt = from_dotnet_datetime(dotnet_dt)
    # python datetime doesn't have a millisecond property so we use microsecond
    assert py_dt.microsecond == 123000
```
This way it is easier to see what is being tested.

And a general advice relevant for bugs, 
1. write a failing test to pin-point the bug
2. Run the tests to check that this tests fails (all other tests should pass)
3. Implement the fix
4. Run the tests to make sure all pass

2023-09-14 12:26 UTC, gedaskir commented on setup.py
> +        "test": ["pytest", "matplotlib", "tk"],
What is the reason to include tk as dependency?

2023-09-14 12:27 UTC, gedaskir commented on mikeio1d/dotnet.py
> +                                      x.second, milliseconds)
Indentation?

2023-09-14 12:28 UTC, gedaskir commented on setup.py
> -    version="0.4.0",
The increase is not strictly necessary, because we have not released 0.4.0 yet, so we could keep the 0.4.0.

2023-09-14 12:28 UTC, ecomodeller commented on mikeio1d/dotnet.py
> +                                      x.second, milliseconds)
The answer is to use https://black.readthedocs.io/en/stable/ 👍

2023-09-14 12:31 UTC, gedaskir commented
As a side note I think we should release version 0.4 after this bug fix :-)

2023-09-14 13:01 UTC, ryan-kipawa commented on setup.py
> +        "test": ["pytest", "matplotlib", "tk"],
When I initially ran pytest, it failed for this test: 'test_result_quantity_collection_methods'. The error was along the lines of:

`_tkinter.TclError: Can't find a usable init.tcl in the following directories`

After pip installing tk, it resolved the issue. If I again remove tk, the test fails.

I don't know if I'm the only one who has this issue, but since I recently freshly installed everything, I figured I would add it to spare anyone else similar troubleshooting. I do agree it's not ideal to have it there - should we remove it?

2023-09-14 13:07 UTC, ryan-kipawa commented on mikeio1d/dotnet.py
> +                                      x.second, milliseconds)
Woops, I'll fix it with black. Thought my vscode extensions had taken care of it..

2023-09-14 14:18 UTC, ecomodeller approved these changes

2023-09-14 15:07 UTC, ryan-kipawa commented on setup.py
> +        "test": ["pytest", "matplotlib", "tk"],
I believe the latest commit from @ecomodeller fixes this in a nice way, thanks!

2023-09-14 15:37 UTC, merged

2023-09-15 08:08 UTC, JesperGr commented
A bit late, but...

.NET is based on a Ticks counter with a resolution of 10000 "ticks" per millisecond. So, .NET actually has sub-microsecond resolution, though you need to work with the ticks value to apply microsecond accuracy.

To store microseconds to a .NET DateTime, do:

```
    dateTime = new DateTime(2022, 9, 15, 10, 09, 08);
    int microsecs = 123456;
    dateTime = dateTime.AddTicks(microsecs*(TimeSpan.TicksPerMillisecond/1000));
```
And to get microseconds out of a .NET timestamp, do:
```
    long microsecsOut = dateTime.Ticks % TimeSpan.TicksPerSecond / (TimeSpan.TicksPerMillisecond / 1000);
```